### ISSUE TITLE
access-token - can't access keys.

### ISSUE THREAD

**Issue by tim-field** [Rydgel/Clojure-Instagram-API#3]
I'm a noob and this this isn't a support forum, but ... any clues as to what is going on here?  With the below access token looks correct ( if print it all I can see the keys & data ) but I can't display it per the example ( or any other way, its like it isn't actually a map structure beyond body)  test-thing value works...

``` clojure
 (defn save-auth [{:keys [params]}]
  (let [code (:code params)
        access-token (get-access-token *creds* code)
        test-thing {:body {:access_token "ted"}} ]
    {:status 200
     :headers {"Content-Type" "text/plain"}
     :body (-> access-token :body :access_token)}))
```

**Comment by timbofield** [comment]
This is what is returned, body: isn't a map, I'm too noob to know how to get things out of it now, or if this is intentional?

```
headers: {content-type: application/json, content-length: '289', connection: keep-alive,
  pragma: no-cache, expires: 'Sat, 01 Jan 2000 00:00:00 GMT', set-cookie: 'csrftoken=9c5bad8727db13908992e479d7f78c6b;
    expires=Sun, 29-May-2016 09:06:25 GMT; Max-Age=31449600; Path=/', date: 'Sun,
    31 May 2015 09:06:25 GMT', vary: 'Cookie, Accept-Language, Accept-Encoding', cache-control: 'private,
    no-cache, no-store, must-revalidate', content-language: en}
status: {code: 200, msg: OK, protocol: HTTP/1.1, major: 1, minor: 1}
body:
  access_token: xxxxx
  user: {username: tfdiddy, bio: '', website: '', profile_picture: 'https://igcdn-photos-e-a.akamaihd.net/hphotos-ak-xtp1/t51.2885-19/11055747_791331110950700_2073441790_a.jpg',
    full_name: Tim, id: '520163296'}
```

**Comment by timbofield** [comment]
I needed to do this to get access_token
```clojure
(get (:body access-token) "access_token")

**Comment by Rydgel** [comment]
Yeah my bad, keys are actually strings. I will update the documentation. Thank you.

**Comment by Rydgel** [comment]
@timbofield I updated my lib to version 0.2.0. It outputs better hashes, so you are not forced to use `get`.

For instance this now works as intended:

``` clojure
(defn save-auth [codeFromIG]
  (let [access-token-request (get-access-token *creds* codeFromIG)
        access-token (-> access-token-request :body :access_token)
        user (-> access-token-request :body :user)]
    {:status 200
     :headers {"Content-Type" "text/plain"}
     :access-token access-token
     :user user}))
```

It always meant to be the case, but the json lib was updated and I didn't notice those changes.
So you can upgrade if you want and your first code version will work (as it was meant to).
Thanks for your feedback.

**Comment by tim-field** [comment]
Thanks @Rydgel version 0.2.0 is working well.
